# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('short', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
