# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
