# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-29 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20161228_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
